<html>
<head>
<title><?= $title ?></title>

<link rel="stylesheet" href="<?= $this->url('css/style.css') ?>" />

<!-- Load css or js define in action -->
<?php foreach ($scripts as $script): ?>
    <?php if ($script->type == "js"): ?>
        <script type="text/javascript" src="<?= $script->path ?>"></script>
    <?php elseif ($script->type == "css"): ?>
        <link rel="stylesheet" href="<?= $this->url($script->path) ?>" />
    <?php endif ?>
<?php endforeach ?>

</head>
<body>
<?= $this->navigation()->render() ?>
<h1><?= $content_title ?></h1>
<?php
$flash = $this->flash()->all();
foreach ($flash as $key => $val) {
    if (count($val)) {
        echo "<ul>";
    }
    foreach ($val as $message) {
        echo sprintf("<li>%s : %s</li>", $key, $message);
    }
    if (count($val)) {
        echo "</ul>";
    }
}
?>
<div>
<?= $content ?>
</div>
</body>
</html>
