<html>
<head>
<title><?= $title ?></title>
</head>
<body>
<?= $this->navigation()->render() ?>
<h1><?= $content_title ?></h1>
<?php
$flash = $this->flash()->all();
foreach ($flash as $key => $val) {
    if (count($val)) {
        echo "<ul>";
    }
    foreach ($val as $message) {
        echo sprintf("<li>%s : %s</li>", $key, $message);
    }
    if (count($val)) {
        echo "</ul>";
    }
}
?>
<div>
<?= $content ?>
</div>
</body>
</html>
